{% set so_number = '164' %}
{% set epoch = '1' %}
{% set version_prefix = epoch + '!' + so_number %}
{% set revision = '3095' %}
{% set version = version_prefix + '.' + revision %}
# This is revision 3095. (git rev-list HEAD | wc -l)
{% set commit = "baee400fa9ced6f5481a728138fed6e867b0ff7f" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: x264
  version: {{ version }}

source:
  # need to use the git source to make version.sh in source work
  git_url: https://code.videolan.org/videolan/x264
  git_rev: {{ commit }}

build:
  number: 0
  run_exports:
    - x264 >={{ version }},<{{ epoch + '!' }}{{ so_number|int + 1 }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler("c") }}
    - perl
    - nasm
    - make
    # m2-git is required, because "git clone" won't work when combining the "git" package with "m2-bash"
    - {{ posix }}git  # [win]
    - {{ posix }}bash  # [win]
    - {{ posix }}coreutils  # [win]
    - {{ posix }}grep  # [win]
    - {{ posix }}sed  # [win]
  host:

test:
  commands:
    - test -f ${PREFIX}/include/x264.h                     # [unix]
    - test -f ${PREFIX}/lib/libx264.a                      # [unix]
    - test -f ${PREFIX}/lib/libx264.dylib                  # [osx]
    - test -f ${PREFIX}/lib/libx264.{{ so_number }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/libx264.so                     # [linux]
    - test -f ${PREFIX}/lib/libx264.so.{{ so_number }}     # [linux]
    - if not exist %LIBRARY_INC%\\x264.h exit 1            # [win]
    - if not exist %LIBRARY_BIN%\\libx264-{{ so_number }}.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\libx264.dll.lib exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\x264.lib exit 1          # [win]
    - x264 --help

about:
  home: http://www.videolan.org/developers/x264.html
  license: GPL-2.0
  license_file: COPYING
  summary: A free software library for encoding video streams into the H.264/MPEG-4 AVC format.

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - carlodri
    - sdvillal
