# {% set version = "20180501" %}
{% set year = '2018' %}
{% set version = year + '0712' %}
{% set next_year = int(year) + 1 %}
{% set sha256 = "c5ad8fc87a4c5f0908027a68feebc345463afc79870c99d560f8edf58783ea7a" %}

package:
  name: x264
  version: {{ version }}

source:
  fn: x264-snapshot-{{ version }}-2245-stable.tar.bz2
  url: http://download.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-{{ version }}-2245-stable.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true         # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - perl
    run_exports:
      - x264 >={{ version }},<{{ next_year }}0000
  host:
    - nasm

test:
  commands:
    - test -f ${PREFIX}/include/x264.h         # [unix]
    - test -f ${PREFIX}/lib/libx264.a          # [unix]
    - test -f ${PREFIX}/lib/libx264.dylib      # [osx]
    - test -f ${PREFIX}/lib/libx264.so         # [linux]
    - x264 --help                              # [unix]

about:
  home: http://www.videolan.org/developers/x264.html
  license: GPL-2.0
  license_file: COPYING
  summary: A free software library for encoding video streams into the H.264/MPEG-4 AVC format.

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - carlodri
