appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Oeg4QOan6LGblaI9oGopI7gNI86Hjdp6gDGxeyfS7KeR89vjiuLDiVqJJ8Z4P4TE/gEvlwrJOLEtIpijaJpyhLG3mkftEtz1XPwHU7lfHOAPCqx5IkHAEFATeQSQCjg0IF/n4iOGeacl/Y8W/Tnn7RG/1Ej8FS+6nUhFcQ2wDcPBb7mkdln3j1+J2faLacwbSnqKCNOFhhoJ3baXHG13idKSfaAJn860r5Y5W0NKz7hfIAUCJBY/0fEgfxeY1G8PDaLN0DnQ73FTnHJMn0xsS6mRfX9rAI+WPttumyiBdSFOsoXJEy+GTlIYSRL1Jh7LhOJcz05d7fofnILoUo8DitiuJQqnaMnssurPZwc+j71Y6AY9TQjOJ0vFQlXYnxRMz++N4npl7tFfcjId3+9oMKbhDljQ8zhBXoTDXJCWn2wQigg56ZAA5I4NCoHu2TCX02+xuDYHuw9Ypq+EUE5sXg/ObHwskktuwGZZiKFFnRMBflRg6bxElYLLOftng+qMhbB5geq+GP86BYawAtua51vulsoNCx9lFqgWueOMuWHx3BTmwLYl/ba0V1kCMGMJvEXyV/QsQ7z8LmtAxaa1nbnjtONqngDH/fCxIPTVEdGLgK1ETH4QI6qp2qLCyHyfz9kfjZb9vZo12owJcBLK7AQOgmVa4JJcYVlMwmJAECc=}
